[package]
name = "setochka"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
bstr = { version = "1.12.1", default-features = false }
env_filter = { version = "2.0.0", default-features = false, features = ["std"] }
log = "0.4.33"
rusqlite = { version = "0.40", default-features = false, features = ["bundled"] }
rusqlite_migration = "2.6"
