[package]
name = "setochka"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
bit-vec = { version = "0.10.1", default-features = false }
bstr = { version = "1.12.1", default-features = false, features = ["alloc"] }
env_filter = { version = "2.0.0", default-features = false, features = ["std"] }
log = "0.4.33"
minijinja = { version = "2.24.0", features = ["json"] }
num-derive = "0.4"
num-traits = "0.2"
rusqlite = { version = "0.40", default-features = false, features = ["bundled"] }
rusqlite_migration = "2.6"
serde = { version = "1.0.229", features = ["derive"] }
serde_urlencoded = "0.7.1"
tiny_http = "0.12.0"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "unwind"
